version: '3.7'

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - .:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

volumes:
  postgres_volume:
  redis_volume:
